defaults:
  - base_config_model
  - weather: clear
  - model: complex
  - variables: complex
  - _self_

host: '127.0.0.1'
port: 2000
asynch: False # Activate asynchronous mode execution
dynamic_weather: False